Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Models/SaleEntities/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectSem3.Models.SaleEntities
{
    public class Cart
    {
    }
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectSem3.Models;
using ProjectSem3.Models.SaleEntities;

namespace ProjectSem3.Controllers
{
    
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Image,Description,Price")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Image,Description,Price")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Controllers/CartController.cs
using ProjectSem3.Models;
using ProjectSem3.Models.SaleEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace ProjectSem3.Controllers
{
    public class CartController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private const string CartSession = "CartSession";

        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [Authorize]
        public ActionResult AddItem(int bookId, int quantity)
        {
            Book book = db.Books.SingleOrDefault(n => n.Id == bookId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Book.Id == bookId))
                {
                    foreach (var item in list)
                    {
                        if (item.Book.Id == bookId) 
                        {
                            item.Quantity += quantity;
                        }   
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.Book = book;
                    item.Quantity = quantity;
                    list.Add(item);
                }
            }
            else
            {
                var item = new CartItem();
                item.Book = book;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);

                //gan vao session
                Session[CartSession] = list;
            }

            return RedirectToAction("Index");
        }
        public ActionResult DeleteItem(int bookId)
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            foreach (var item in list)
            {
                if (item.Book.Id == bookId)
                {
                    list.Remove(item);
                    break;
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult UpdateCart(FormCollection fc)
        {
            string[] quantities = fc.GetValues("quantity");
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            for (int i = 0; i < list.Count; i++)
            {
                list[i].Quantity = Convert.ToInt32(quantities[i]);
            }
            Session[CartSession] = list;

            return RedirectToAction("Index");
        }
        public ActionResult Payment()
        {
           
            return View("Payment");
        }
        public ActionResult ProcessOrder(FormCollection fc)
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }

            // 1.save into order
            Order order = new Order()
            {
                UserId = User.Identity.GetUserId(),
                DateOrder = DateTime.Now,
                Payment = fc["payment"],
                Status = "da dat hang",
                Description = fc["description"]
            };
            db.Orders.Add(order);
            db.SaveChanges();


            // 2.save into orderdetail
            foreach (CartItem cartItem in list)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderId = order.Id,
                    BookId = cartItem.Book.Id,
                    Quantity = cartItem.Quantity,
                    TotalPrice = cartItem.Book.Price
                };
                db.OrderDetails.Add(orderDetail);
                db.SaveChanges();
            }
            
            // 3.Remove shopping cart session
            Session.Remove(CartSession);

            return View("OrderSuccess");
        }
    }
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Cart/Index.cshtml
@model List<ProjectSem3.Models.SaleEntities.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("UpdateCart", "Cart", FormMethod.Post))
{
    <table class="table">
        <thead>
            <tr>
                <td>ID Product</td>
                <td>Name Product</td>
                <td>Image</td>
                <td>Quantity</td>
                <td>Unit Price</td>
                <td>Total Price</td>
            </tr>
        </thead>
        <tbody>
            @{
                int Total = 0;
            }
            @foreach (var item in Model)
            {
                int lineTotal = Convert.ToInt32(item.Quantity * item.Book.Price);
                Total = Convert.ToInt32(@Total + lineTotal);
                <tr>
                    <td>@item.Book.Id</td>
                    <td>@item.Book.Title</td>
                    <td><img src="@item.Book.Image" width="60" /></td>
                    <td><input type="text" name="quantity" value="@item.Quantity" /></td>
                    <td>@item.Book.Price</td>
                    <td>@(item.Book.Price * item.Quantity)</td>
                    <td>
                        <button class="btn-success">@Html.ActionLink("Delete", "DeleteItem", "Cart", new { bookId = item.Book.Id }, null)</button>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="5" class="text-right"><b>Total: @Total</b></td>
            </tr>

        </tbody>
    </table>
    <br />
    @Html.ActionLink("Countinue Shopping", "Index", "Books", null, new { @class = "btn btn-primary btn-large" })

    <input type="submit" value="UpdateCart" />

    @Html.ActionLink("Payment", "Payment", "Cart", null, new { @class = "btn btn-primary btn-large" })
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Cart/OrderSuccess.cshtml
@{
    ViewBag.Title = "OrderSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OrderSuccess</h2>
<h2>Please click to here @Html.ActionLink("Home", "Index", "Home") to go to home page.</h2>

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Cart/Payment.cshtml
@using ProjectSem3.Models.SaleEntities;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    if (Session["CartSession"] != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <td>ID Product</td>
                    <td>Name Product</td>
                    <td>Image</td>
                    <td>Quantity</td>
                    <td>Unit Price</td>
                    <td>Total Price</td>
                </tr>
            </thead>
            <tbody>
                @{
                    int Total = 0;
                }
                @foreach (var item in (List<CartItem>)Session["CartSession"])
                {
                    int lineTotal = Convert.ToInt32(item.Quantity * item.Book.Price);
                    Total = Convert.ToInt32(@Total + lineTotal);
                    <tr>
                        <td>@item.Book.Id</td>
                        <td>@item.Book.Title</td>
                        <td><img src="@item.Book.Image" width="60" /></td>
                        <td><input type="text" name="quantity" value="@item.Quantity" readonly /></td>
                        <td>@item.Book.Price</td>
                        <td>@(item.Book.Price * item.Quantity)</td>
                    </tr>
                }
                <tr>
                    <td colspan="5" class="text-right"><b>Total: @Total</b></td>
                </tr>

            </tbody>
        </table>
    }
    else
    {
        <h4>No item in your cart!</h4>
    }

}
<br />
@using (Html.BeginForm("ProcessOrder", "Cart", FormMethod.Post))
{
    <table>
       @* <tr>
            <td>User Name: </td>
            <td><input type="text" name="username" /></td>
        </tr>
        <tr>
            <td>Email: </td>
            <td><input type="text" name="email" /></td>
        </tr>
        <tr>
            <td>Address: </td>
            <td><input type="text" name="address" /></td>
        </tr>*@
        <tr>
            <td>Description: </td>
            <td><input type="text" name="description" /></td>
        </tr>
        <tr>
            <td>Payment by: </td>
            <td><input type="text" name="payment" /></td>
       @* <td>
            @Html.DropDownList("ddl3", new List<SelectListItem>
                {
                new SelectListItem {Text = "Shipper", Value = "1"},
                new SelectListItem {Text = "COD", Value = "2"}
                }, "--- Select ---")
        </td>*@
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Process Order" /></td>
        </tr>

    </table>
}