Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ProjectSem3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectSem3.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Role
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);
        }
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        [HttpGet]
        public ActionResult CreateRole()
        {
            var role = new IdentityRole();
            return View(role);
        }

        [HttpPost]
        public ActionResult CreateRole(IdentityRole identity)
        {
            //var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_db));
            context.Roles.Add(identity);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ProjectSem3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectSem3.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Users
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (isAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();
        }
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        public ActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateUser(FormCollection form)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            string username = form["txtUserName"];
            string address = form["txtAddress"];
            string email = form["txtEmail"];
            string password = form["txtPassword"];

            var user = new ApplicationUser();
            user.UserName = username;
            user.Address = address;
            user.Email = email;

            var newuser = UserManager.Create(user, password);
            return View();
        }
        public ActionResult AsignRole()
        {
            ViewBag.Roles = context.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult AsignRole(FormCollection form)
        {
            string username = form["txtUserName"];
            string rolename = form["RoleName"];
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(username, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            userManager.AddToRole(user.Id, rolename);
            return View("Index");
        }
    }
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Users/AsignRole.cshtml
@{
    ViewBag.Title = "AsignRole";
}

<h2>AsignRole</h2>


+@using (Html.BeginForm("AsignRole", "Users", FormMethod.Post))
{
<div class="row">
    <div class="col-md-6">
        <label class="control-label">UserName</label>
        <input type="text" name="txtUserName" class="form-control" />
    </div>

    <div class="col-md-6">
        <label class="control-label">Select Role</label>
        @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select...")
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Users/CreateUser.cshtml
@{
    ViewBag.Title = "CreateUser";
}

<h2>CreateUser</h2>
@using(Html.BeginForm("CreateUser", "Users", FormMethod.Post))
{
<div class="row">
    <div class="col-md-6">
        <label class="control-label">User Name</label>
        <input type="text" name="txtUserName" class="form-control" />
    </div>
    <div class="col-md-6">
        <label class="control-label">Address</label>
        <input type="text" name="txtAddress" class="form-control" />
    </div>
    <div class="col-md-6">
        <label class="control-label">Email</label>
        <input type="text" name="txtEmail" class="form-control" />
    </div>
    <div class="col-md-6">
        <label class="control-label">Password</label>
        <input type="text" name="txtPassword" class="form-control" />
    </div>

</div>
<div class="row">
    <div class="col-md-12">
        <button type="submit" value="Submit" class="btn btn-primary">Save</button>
    </div>
</div>
}

Group3_SellingCakeRecipes_T1911E/Source code/Group_Project_Sem_3-dev_ka/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (ViewBag.displayMenu == "Yes")
{
    <h1>Welcome Admin. Now you can create user Role.</h1>
    <ul>
        <li>@Html.ActionLink("Create User", "CreateUser", "Users")</li>
        <li>@Html.ActionLink("Asign Role User", "AsignRole", "Users")</li>
        <li>@Html.ActionLink("Manage Role", "Index", "Role")</li>
    </ul>
}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) .We will add user module soon </h2>
}